### ISSUE TITLE
Does not ignore process.env references in comments

### ISSUE THREAD

**Issue by bhumijgupta** [hackcode-packages/env-example-generator#1]
# Steps to reproduce
1. Create a js/ts file like
```js
const demo = ()=>{
	// In older versions, it was called process.env.ID but replaced for semantic purposes
	const a = process.env.GOOGLE_ID
}
```
2. Generate env file through `generate-env`

## Expected Output
.env.example only contains GOOGLE_ID as key

## Actual Output
.env.example file generated contains both GOOGLE_ID and ID as keys

**Comment by bhumijgupta** [comment]
I'd like to create a PR if this is up for grabs

**Comment by YashKumarVerma** [comment]
Sure, thanks a lot !
